### ISSUE TITLE
Data cannot be downloaded

### ISSUE THREAD

**Issue by spiderman0914** [SAR-EDU/tomography#2]
Hi @jonas-eberle @x4ecro @felixcremer @johntruckenbrodt 
The code you wrote looks great, but I get a ‘502 bad gateway' when I want to download the test data (I think it may be a server problem, and I also get a 502 when I check the EO College website for tutorials around 2017). Can you help me with this problem?
 Coming from a beginner in the SAR field.
Thank you all

**Comment by spiderman0914** [comment]
oh I have already solved this problem

**Comment by johntruckenbrodt** [comment]
Hi @spiderman0914, sorry for the late reply. Good that you were able to solve it yourself.
Cheers, John
