### ISSUE TITLE
install tomography module on Ubuntu

### ISSUE THREAD

**Issue by KarimaMarina** [SAR-EDU/tomography#3]
Dear John,
Please I do have an issue with the last step in the installation of the tomography module. The following provides the error pointed out in the attached PNG file: 
sudo python3 -m pip install tomography_tutorial

![Capture_error_pillow](https://user-images.githubusercontent.com/99021801/163799799-57f3bf1e-8289-4dc3-8636-a9f06d8f7b54.png)

I hope you can help me fix it and thank you.
Karima.

**Comment by johntruckenbrodt** [comment]
Hi @KarimaMarina. As the message says, you are missing some zlib files. Have a look if that helps:
https://itsfoss.com/install-zlib-ubuntu/

**Comment by johntruckenbrodt** [comment]
closing this as there hasn't been an update in over a month. Feel free to reopen if necessary.
