### ISSUE TITLE
GeoViewer

### ISSUE THREAD

**Issue by njw2023** [SAR-EDU/tomography#4]
Hi dear John
There is a program error in epsg = int(srs.GetAuthorityCode(None)) which TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'.
I don't know why it went wrong. Please help me，Thanks a lot.
Best regards,
Frank

**Comment by johntruckenbrodt** [comment]
Hi @njw2023. This kind of error might occur if the CRS does not have an EPSG representation. What is the CRS of your input data?
Here is a reproducible independent example:
```python
from osgeo import osr
srs = osr.SpatialReference()
srs.SetFromUserInput('EPSG:4326')
srs.AutoIdentifyEPSG()
code = int(srs.GetAuthorityCode(None))
print(code)
```

See here for a more comprehensive function for converting between different CRS representations:
https://spatialist.readthedocs.io/en/latest/spatialist.html#spatialist.auxil.crsConvert

**Comment by njw2023** [comment]
Thanks for that piece of advice!That solved my issue.

**Comment by johntruckenbrodt** [comment]
You're welcome
