### ISSUE TITLE
data is no longer available

### ISSUE THREAD

**Issue by johntruckenbrodt** [SAR-EDU/tomography#5]
@x4ecro the URL for download of the data is down. Could you check?
https://eo-college.org/Data/Tomography/tomography_data.zip

**Comment by x4ecro** [comment]
@johntruckenbrodt where is this link used? the recent downlaod link for the data package is https://cloud.uni-jena.de/s/9o8r4zs2D852HdT. the ReadME.md points to the correct file.

**Comment by johntruckenbrodt** [comment]
Ah right, you changed link in the README and I forgot about it. The notebook still contains the old link.
