### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by DuoAp** [SAR-EDU/tomography#6]
The Data link in the Readme.md doesn't seem to be available now

**Comment by johntruckenbrodt** [comment]
@DK05310214 thanks for reporting. @x4ecro could you check? Now the FSU Cloud link is broken:
https://cloud.uni-jena.de/s/9o8r4zs2D852HdT

**Comment by x4ecro** [comment]
@DK05310214 @johntruckenbrodt the issue should be fixed now. 
Let me know if you discover other instances of broken links as we had to renew all permanent download links from the cloud very recently.

**Comment by johntruckenbrodt** [comment]
The link is in the README and in the Juypter notebook. With this it is fixed: https://github.com/EO-College/tomography_tutorial/commit/1073ccfaca358bce95e6fd78f2d52ec2f8ee06cd
